version: "2"

services:
  app:
    image: harbor.ath.tamu.edu/ait/authproxy:1.1
    build: .
    volumes:
      - ./tenants.json:/usr/src/app/tenants.json
      - ./server.js:/usr/src/app/server.js
    ports:
      - 3000:3000
    command: npm run dev
